# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField(default='defaultURL')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
